### ISSUE TITLE
1.18.2purpur报错,启动报错

### ISSUE THREAD

**Issue by lizheyo77** [Lings-MC/LingsHTTPUtils#9]
启动报错
--------------------------------
[01:56:28] [Server thread/ERROR]: Error occurred while enabling LingsHttpUtils v1.2.3 (Is it up to date?)
java.lang.IllegalArgumentException: null
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1303) ~[?:?]
	at cn.lingsmc.lingshttputils.asyncworkers.WorkerOptions.runWorkers(WorkerOptions.java:37) ~[LingsHTTPUtils-1.2.3.jar:?]
	at cn.lingsmc.lingshttputils.LingsHttpUtils.onEnable(LingsHttpUtils.java:93) ~[LingsHTTPUtils-1.2.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:56:28] [Server thread/INFO]: [LingsHttpUtils] Disabling LingsHttpUtils v1.2.3
[01:56:28] [Server thread/INFO]: [LingsHttpUtils] 尝试关闭Cycle Workers...
[01:56:28] [Server thread/ERROR]: Error occurred while disabling LingsHttpUtils v1.2.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ExecutorService.shutdownNow()" because "cn.lingsmc.lingshttputils.asyncworkers.WorkerOptions.threadPool" is null
	at cn.lingsmc.lingshttputils.asyncworkers.WorkerOptions.stopWorkers(WorkerOptions.java:65) ~[LingsHTTPUtils-1.2.3.jar:?]
	at cn.lingsmc.lingshttputils.LingsHttpUtils.onDisable(LingsHttpUtils.java:100) ~[LingsHTTPUtils-1.2.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]启
--------------------------------
重载报错
--------------------------------
[01:57:07] [Server thread/WARN]: Unexpected exception while parsing console command "lingshttputils reload"
org.bukkit.command.CommandException: Cannot execute command 'lingshttputils' in plugin LingsHttpUtils v1.2.3 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:868) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1606]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Crsuh2er0** [comment]
v1.2.4中已修复
#10

**Comment by Crsuh2er0** [comment]
很抱歉 v1.2.3没跑高版本测试

**Comment by lizheyo77** [comment]
> 很抱歉 v1.2.3没跑高版本测试

我会尽快测试一下

**Comment by Crsuh2er0** [comment]
1.2.5已修复reload指令
